### PR TITLE
Update #792 to SP_BLITZ, because SQL express editions need an extra traceflag to fully enable DAC

### PR DESCRIPTION
**Pull request by Totty1973**
Update #792 to SP_BLITZ, because SQL express editions need an extra traceflag to fully enable DAC

Fixes # 792

Changes proposed in this pull request:
 - new warning 'Remote DAC switched on but needs traceflag 7806'  on express edition

How to test this code:
 - have enabled TF7806 and DAC enabled when using Express edition: no warning
 - have disabled TF7806 (default) and DAC enabled when using Express edition: new warning 'Remote DAC switched on but needs traceflag 7806'  
 - have DAC disabled: only old warning

Has been tested on (remove any that don't apply):
 - SQL 2012 sp3 express
 - SQL 2014 enterprise

### CODE REVIEW

**Comment by Totty1973** [comment]
I don't see how populatin #tracestatus just once can be achieved if a user can elect not to run all checks

**Comment by BrentOzar** [comment]
By doing it once at the beginning of the proc, or prior to the check you're doing.

I totally understand where you're coming from, I just don't want to redo work in the proc if necessary. A good example might be doing your code later in the proc, after #TraceStatus has been populated, and then checking to see if #TraceStatus already has data in it. If not, run your query.

**Comment by Totty1973** [comment]
> after #TraceStatus has been populated, 
It could be empty because the user choose not to enable any flags, my 2014web-instance does not have any flags set. 
I do not see any flag in version 20170307 saying "i did my query but i still may be empty". Is that the best way?
I could move the procedure to fill the #tracestatus into a global section, so that it gets executed every single time. is that the best way?

**Comment by BlitzErik** [comment]
Haven't seen anything on this in a while, so going to close out for now. If you want to work on it in the future, you can reopen.

Thanks!

**Pull request closed without merging**
