### PR TITLE
Update Merge Blitz.ps1 so not hardcoded to directory path

### PR DESCRIPTION
**Pull request by DanielLoth**
# Overview

This change updates the script such that it'll run on other peoples' machines, even when they don't have a folder path that is specific to Brent's developer machine.

# Testing notes

## Running `Merge Blitz.ps1` from the repository root directory

Command:
```
& '.\Documentation\Development\Merge Blitz.ps1'
```

Demo:
```
PS C:\Dev\SQL-Server-First-Responder-Kit> git status
On branch update-merge-ps1-script
Your branch is up to date with 'origin/update-merge-ps1-script'.

nothing to commit, working tree clean
PS C:\Dev\SQL-Server-First-Responder-Kit> & '.\Documentation\Development\Merge Blitz.ps1'
PS C:\Dev\SQL-Server-First-Responder-Kit> git status
On branch update-merge-ps1-script
Your branch is up to date with 'origin/update-merge-ps1-script'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Install-All-Scripts.sql
        modified:   Install-Azure.sql

no changes added to commit (use "git add" and/or "git commit -a")
```

## Running `Merge Blitz.ps1` from the same directory

Command:
```
& '.\Merge Blitz.ps1'
```

Demo:
```
PS C:\Dev\SQL-Server-First-Responder-Kit\Documentation\Development> git status
On branch update-merge-ps1-script
Your branch is up to date with 'origin/update-merge-ps1-script'.

nothing to commit, working tree clean
PS C:\Dev\SQL-Server-First-Responder-Kit\Documentation\Development> & '.\Merge Blitz.ps1'
PS C:\Dev\SQL-Server-First-Responder-Kit\Documentation\Development> git status
On branch update-merge-ps1-script
Your branch is up to date with 'origin/update-merge-ps1-script'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../../Install-All-Scripts.sql
        modified:   ../../Install-Azure.sql

no changes added to commit (use "git add" and/or "git commit -a")
```

### CODE REVIEW

**Comment by BrentOzar** [comment]
Hi, can you tell me a little about the use case for this?

**Comment by DanielLoth** [comment]
Hi. Same use case as before - combines the various scripts. But now the correct operation of the script isn't dependent on the repository being checked out to the very specific `/Users/brentozar/LocalOnly/Github/SQL-Server-First-Responder-Kit` directory path.

**Comment by BrentOzar** [comment]
Right, but why do YOU need to build the installation scripts for the distribution of the First Responder Kit? You sound like a nice guy, I’m sure, but I’m not looking for you to take over maintenance of the repo. ;-) ---Tiny glass keyboardTypos flowing like riversAs winter snow thawsOn Dec 7, 2024, at 6:54 PM, Daniel Loth ***@***.***> wrote:﻿
Hi. Same use case as before - combines the various scripts. But now the correct operation of the script isn't dependent on the repository being checked out to the very specific /Users/brentozar/LocalOnly/Github/SQL-Server-First-Responder-Kit directory path.

**Comment by DanielLoth** [comment]
Oh, I don't. I was just looking through the repo while doing your course on using it, tried to run the script, and found it didn't work.

**Comment by BrentOzar** [comment]
OK, gotcha. Let's hold off on changing code without a use case for now, and if you'd like to contribute further, make sure to check out the contribution instructions in the repo. Thanks though!

**Pull request closed without merging**
