### PR TITLE
dbo.SqlServerVersions - little change in object existence check + allow script execution

### PR DESCRIPTION
**Pull request by jeffchulg**
Changes proposed in this pull request:
 - object existence includes schema name (with OBJECT_ID built-in function)
 - a "GO" between object creation and DELETE statement
- a "GO" at the end of the script

How to test this code:
- run it as you are used to

Has been tested on (remove any that don't apply):
 - SQL Server 2014

### CODE REVIEW

**Comment by BlitzErik** [comment]
@jeffchulg thanks for this. Can you open a corresponding issue for it? I'll get it merged in as soon as you do.

**Comment by BlitzErik** [comment]
@jeffchulg doing this here isn't the best idea, because when the script gets regenerated, it'll be overwritten. It'd have to happen [over here](https://github.com/jadarnel27/SqlServerVersionScript). Open an issue for @jadarnel27 in his repo.

**Comment by jadarnel27** [comment]
@jeffchulg yep, I'm happy to make that change if you want to create an issue.  Or if you're comfortable with C#, I'm open to a PR as well!

**Comment by jeffchulg** [comment]
@jadarnel27  yes, it could be great. 
I'm not comfortable with C#

**Pull request closed without merging**
