### PR TITLE
Power BI Report Pages Update For Phone Layout

### PR DESCRIPTION
**Pull request by hfleitas**
Update the FirstResponderKit Example for Training (pbix) and
FirstResponderKit (pbt - template) Power BI file(s) by including
visualizations and controls in Phone layout view. This allows the
report pages to be used in a more tailored view from a Phone with
the Power BI app.

Add Feature.

Update Pages:
 - Overview
 - Query Details
 - File Speeds
 - File Sizes
 - Perfmon
 - Wait Stats Anomalies
 - Perfmon Anomalies
 - Instructions

Fixes https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1809.

Changes proposed in this pull request:
 - Update the FirstResponderKit Example for Training (pbix) and FirstResponderKit (pbt - template) Power BI file(s) by including visualizations and controls in Phone layout view. 
 - This allows the report pages to be used in a more tailored view from a Phone with the Power BI app.

How to test this code:
 - Navigate to /SQL-Server-First-Responder-Kit/Power BI/
 - Open file [FirstResponderKit Example for Training.pbix]
 - Click View > Phone Layout
 - Repeat for all pages.
 - Scroll down to see content
 - Click File, Exit
 - Open file [FirstResponderKit.pbit]
 - Specify the Instance and Database, then click Load
 - Click View > Phone Layout
 - Click on each page Query Details > File Speeds > File Sizes > Perfmon > Wait Stats Anomalies > Perfmon Anomalies > Instructions
 -  Scroll down to see content
 - Click File > Publish > Publish to Power BI
 - Save your changes to your file system, specify a file name. ie. BlitzDev.pbix, then click Save.
 - Sign-in to the Power BI service from Power BI Desktop
 - Destination > click My workspace > Select
 - Replace dataset if prompted
 - Should say Success!, click Got it > File > Exit
 - On your mobile open the IOS App Store or Google Play Store
 - Search for Microsoft Power BI and press Open/Get/Install.
 - Sign-in to the Power BI service using the same credentials as in the previous step.
 - Press the Burger Menu > My workspace > Reports. 
 - Press the new report BlitzDev or whatever you decided to call it.
 - 💣 💥 
 - Press the Pages icon on the bottom right, switch to each page.
 - Press the Ellipses on the top right per visual > Expand to focus mode to see more details.
 - Press the < on the top left to return
 - Rotate your phone horizontally for the standard desktop view. 💣 
 - Rotate your phone vertically for the phone view. 💥 
 - 😄 ✔️ 

Has been tested on (remove any that don't apply): Yes.
 - Case-sensitive SQL Server instance
 - SQL Server 2017

### CODE REVIEW

**Comment by EmanueleMeazzo** [comment]
Seems to work ok, the only weird thing is the warning that pops up when opening the pbix files, which may freak out some folks

image

**Comment by hfleitas** [comment]
Its almost halloween 🎃 👻 🎃 why you worried? lol Which version of PBI Desktop are you using? We can restripe the file and commit again if needed. That msg reads like a fwd compat warning if you save the file with a previous version of PBI and later open it in a newer version. Are you getting pbi updates pendings messages too? I'm using [Version: 2.61.5192.641 64-bit (August 2018)](https://www.microsoft.com/download/details.aspx?id=57271). Btw, when you publish to PBIRS = unlimited scheduled refresh. Lastly, not sure if I missed it, but does the repo spec PBI version to support in the Contribute instructions? Thx, Hiram

**Comment by hfleitas** [comment]
@BrentOzar Is this going to get merged? Do you need me to do anything else? I'd also like to enable the [bookmark](https://docs.microsoft.com/en-us/power-bi/desktop-bookmarks) feature for the pbix. This lets you save filters on panes. I find myself using the perfmon tab a lot and clicking on several counters very often so would be great if there were bookmarks for them already or at least to have the feature enabled on the pbix file. We can do that as a speperate PR, if you like how that sounds lmk. Thx!

**Comment by kendalllister** [comment]
Looks good to me so far, testing on SQL Server 2014 and an iPhone X.

**Comment by BrentOzar** [comment]
Looks good, thanks sir!

**Pull request merged**
