### PR TITLE
Issue 1245

### LINKED ISSUE #1245: sp_DatabaseRestore -- Error handling
Right now, if a restore fails in sp_AllNightLog, the error message doesn't bubble up and isn't handled anywhere.

`sp_AllNightLog` calls `sp_DatabaseRestore` which calls `dbo.CommandExec`

I believe we need to call `dbo.CommandExec` in `@Mode 2` in `sp_DatabaseRestore`.

This will give us the full error, the next step is to have `sp_DatabaseRestore` catch error messages, both from `dbo.CommandExec` and in itself.

### PR DESCRIPTION
**Pull request by BlitzErik**
Fixes #1245 

Changes proposed in this pull request:
This is a test PR to see if there are conflicts.

How to test this code:
Hold onto your butt.

Has been tested on (remove any that don't apply):
 - Case-sensitive SQL Server instance
 - SQL Server 2016

### CODE REVIEW

**Comment by BrentOzar** [comment]
@reharmsen sure, if you want support for that, you can create an issue for it and do the code. We focus on building support for the way we use the code, but if you've got a different use case, you'd be the best one to build that code and test it.

Check out the contributing guide for how to get started:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

**Comment by reharmsen** [comment]
@BrentOzar 
I will probably first have to wait for this PR to be merged, as this PR introduces the 'hardcoded' master.

At least I am not seeing any options within GitHub / GitHub Desktop to develop against this PR.
note: I'm busy learning to work with GitHub.

**Comment by BrentOzar** [comment]
@reharmsen no problem! Just go ahead and create the issue for it first if you like, and as you're learning, you can read about how to download the contents of a pull request directly, and work on that code if you want.

**Comment by BlitzErik** [comment]
Closing this, not a priority at the moment.

**Pull request closed without merging**
