### PR TITLE
TraceFileIssue check on 106

### LINKED ISSUE #1761: sp_Blitz - Trace File Issue
**Do you want to request a *feature* or report a *bug*?**
Bug. 

**What is the current behavior?**

I'm on a client server and somebody's been messing with the trace files by the looks of it. When it gets to the appropriate line it sets @TraceFileIssue to 1. This is expected, but it's then throwing errors on check number 106 (which uses this trace file). 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

It's easy enough to add in a line somewhere that changes @base_tracefilename to an invalid location, somewhere before the check for @TraceFileIssue. 

**What is the expected behavior?**

Well, it'd be nice if it didn't throw this error :). I've added AND TraceFileIssue = 0 to check 106 to fix it in my instance.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

This is on SQL 2012 Standard (11.0.7001) but I'd imagine it's not an issue with the version specifically.

### PR DESCRIPTION
**Pull request by RichBenner**
Added @TraceFileIssue = 0 check to number 106.

Fixes #1761  .

Changes proposed in this pull request:
 - Added check for trace file issue to number 106 

How to test this code:
 - Mess about and delete your log files, it'll set @TraceFileIssue to 1. This new check should stop it throwing an error at check 106.

Has been tested on (remove any that don't apply):
 - SQL Server 2016

### CODE REVIEW

**Comment by RichBenner** [comment]
Oh shoot, this should have been on row 7565 along with the check for 106. Checking my actual code I wrapped check 106 in an IF statement to check if @TraceFileIssue = 0 before it runs that check. 

What's the best way of correcting this, shall I put in a different pull request?

**Comment by BlitzErik** [comment]
You should just be able to add more commits to your current PR.

**Comment by RichBenner** [comment]
Ok, so I used the online editor and added in the @TraceFileIssue check that's used for other checks for consistency. Apparently GitHub hates everything about what I've done on this pull request and thinks I've changed a *bunch* of stuff. 

Looking at it, is that just because sp_Blitz has had an update since the time I submitted this PR? things like @UsualDBOwner are definitely already in the repository.

**Comment by BlitzErik** [comment]
Yep, you'll either need to update your branch from dev to rebase it, or just start from scratch with a fresh pull. Up to you!

**Comment by RichBenner** [comment]
I think at this point I'll just start from scratch, I'll close this one and give it up as a case of 'go away and try again'

**Pull request closed without merging**
