### PR TITLE
Updated DatabaseRestore to support versions from 2008 forward.

### LINKED ISSUE #774: DatabaseRestore - add support for SQL Server 2008 - 2014
**Do you want to request a *feature* or report a *bug*?**

Request a feature

**What is the current behavior?**

DatabaseRestore only supports SQL Server 2016.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**

Use dynamic SQL to allow DatabaseRestore to handle the results from RESTORE HEADERONLY and RESTORE FILELISTONLY in SQL Server 2008-2014, allowing DatabaseRestore to be executed in these versions.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server 2008
SQL Server 2008R2
SQL Server 2012
SQL Server 2014

### PR DESCRIPTION
**Pull request by jeffrosenberg**
Altered code for capturing RESTORE statement output to use dynamic SQL and capture columns based on version number. Changed table vars to temp tables to work with the dynamic SQL.

Fixes #774 .

Changes proposed in this pull request:
 - Updated DatabaseRestore to use dynamic SQL for capturing columns from RESTORE HEADERONLY and RESTORE FILELISTONLY, allowing it to be used from SQL Server 2008 onwards.

How to test this code:
 - Obtain a backup from the version of SQL Server you want to test
 - Verify it can be restored successfully to SQL Server 2016 (regression test)
 - Verify it can be restored successfully to the target version of SQL Server (new feature test)

Has been tested on (remove any that don't apply):
 - SQL Server 2008 R2
 - SQL Server 2014
 - SQL Server 2016

### CODE REVIEW

**Comment by BlitzErik** [comment]
Hi Jeff,

Wanted to merge this but it's showing some conflicts. Can you take a look?

Thanks

**Comment by jeffrosenberg** [comment]
Sure, I'll look tonight. Guessing Git is confused now that my earlier PRs have been merged, I'll get it cleaned up.

**Comment by jeffrosenberg** [comment]
@BlitzErik conflicts are resolved, and I've done new tests in SQL Server 2014 and 2008 R2 to confirm that it's working.

**Comment by BlitzErik** [comment]
@jeffrosenberg looks good! Thanks!

**Pull request merged**
