### PR TITLE
AppVeyor CI Integration

### PR DESCRIPTION
**Pull request by SelmanAY**
hi,

### what this feature does: 
  - using appveyor server creates a clean installation of three sql server installations (2008r2, 2012sp1, 2014)
  - runs the scripts to these instances
    * if installation fails the build will fail
    * these installations does not contains ReportServer database (so sp_BlitzRS fails to install) so in install.ps1 file I have checked if ReportServer databases exits, if so i run the script file. in short sp_BlitzRS is nor actually been installed or tested. 
    * test script files (in test.sql i have add a test for _ characters in parameters.)
    * if the build was a tagged build appveyor puts script files in a zip file and push this artifact back to github in releases tab. 

### what i changed : 
I only added files
  - appveyor.yml
  - install.ps1
  - test.sql
and added two more badges to the readme.md (i don't understand why it shows too many changes)

### how to use it :
in order to use this feature you need to 
1. create an appveyor account from appveyor.com
2. create a token from github. (https://github.com/settings/tokens) (for permissions look at https://www.appveyor.com/docs/deployment/github search for text 'GitHub authentication token')
3. encrypt the token using https://ci.appveyor.com/tools/encrypt
4. put encrypted data to appveyor.yml file

### CODE REVIEW

**Comment by AndySchwabe** [comment]
I think this will have problems because sp_AskBrent is now named sp_BlitzFirst. 
Also wouldn't it be good to make sure that the SQL Servers AppVeyor is using are CS AS for collations? I think that was the minimum for testing. I didn't see anything in the YAML file that specified a collation for the various servers.

**Comment by SelmanAY** [comment]
Servers are pre installed. In yaml files only services are started.

For sp_AskBrent, since i was started integration before name change i have forgotten to change Thé names in scripts.

**Comment by AndySchwabe** [comment]
Ah okay cool! I wasn't sure if it was building from scratch or just starting prebuilt stuff.

**Comment by SelmanAY** [comment]
I Have changed sp_AskBrent to sp_BlitzFirst. 
thanks @AndySchwabe for reminding.

**Comment by BrentOzar** [comment]
@SelmanAY - howdy sir! I keep saying, "Today's gonna be the day I test this out," and then other stuff happens. I'm really excited about doing this, and I hope to get to it in the next couple of days. I've just never used Appveyor before, so I've got some digging to do in order to get it tested.

I'll keep you posted as soon as I get some free time though. This looks great!

**Comment by Jorriss** [comment]
I'll take a look at this. It just so happens that Dad gave me the AppVeyor keys. Vrooooom!

**Comment by SelmanAY** [comment]
I want to ask something. if i do some other changes to my repository (SelmanAY/SQL-Server-First-Responder-Kit), does this pull request affected from my new changes?

What if i delete my repo? will you be able to do this merge anyway?

PS: Asked just for learning Git.

**Pull request closed without merging**
