### PR TITLE
(build) Add Matrices for SQL Server Version and Collation

### PR DESCRIPTION
**Pull request by SeanKilleen**
Supports #3418.

Saw the blog post, figured I'd try to help a little. :)

This should allow you to specify multiple versions and collations and have them all run as part of a build.

We're not demonstrating this here, but you can also specify specific pairs of values rather than all combinations, if that makes more sense. Happy to adapt according to your needs.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
@BrentOzar FYI you'll have to approve this workflow in order for it to start running for us to check it.

**Comment by BrentOzar** [comment]
Does this also run the test scripts against all of the combinations? I'm guessing not, especially since they'd be on different ports, but I might be missing something obvious.

**Comment by SeanKilleen** [comment]
@BrentOzar we'll have to see once you allow the build to run 😅 

But seriously, what this does is essentially turn this one build into 4 builds. It will currently run the scripts listed in the build against:

* 2017 + SQL_Latin1_General_CP1_CS_AS
* 2019 + SQL_Latin1_General_CP1_CS_AS
* 2022 + SQL_Latin1_General_CP1_CS_AS

**Comment by SeanKilleen** [comment]
@BrentOzar pinging on this just in case you meant to get to it. This is the last time I'll ping on this one so as not to be annoying. 👍 

You'll need to click the button at the bottom of this pull request to enable matriced build, which will then run and I can tweak based on what I see.

**Comment by BrentOzar** [comment]
@SeanKilleen OK, merged. Between you and me, I'm pretty uncomfortable with this style of "merge it and see what happens" development in the repo. I'm going to do it this one time, but going forward, when you wanna wing it, can you do those kinds of tests in your own repo? That way, when you're confident that it's going to work well, and you've got screenshots & explanations of what the code is doing, you can add those here to make me feel more comfortable. Thanks for understanding - I just have a day job and family commitments too, and I gotta be careful about "oopsie" deployments.

**Comment by SeanKilleen** [comment]
@BrentOzar I think you misunderstood my aim. I didn't want you to merge it.

In GitHub, when you add a new GitHub action or modify it, the owner of the repo has to allow it to run within the PR. This is to make sure that nobody can propose an action change and have something run that the repo owner might not intend. This doesn't merge the PR; it just allows the modified build to run against the PR.

I was actually trying to do the opposite of wing it; I was trying to ensure the build ran directly before a merge. @DavidWiseman can verify what I'm saying.

Happy to discuss how GitHub actions work anytime you'd like 👍

**Comment by BrentOzar** [comment]
I really wish I had the time to dig more deeply into it, have the conversations, etc, but I'm just slammed right now. (As evidenced by the 3AM Github work, heh.)

What specific actions do you need me to take right now?

**Comment by SeanKilleen** [comment]
@BrentOzar I think you misunderstood my aim. I didn't want you to merge it.

In GitHub, when you add a new GitHub action or modify it, the owner of the repo has to allow it to run within the PR. This is to make sure that nobody can propose an action change and have something run that the repo owner might not intend. This doesn't merge the PR; it just allows the modified build to run against the PR.

I was actually trying to do the opposite of wing it; I was trying to ensure the build ran directly before a merge. @DavidWiseman can verify what I'm saying.

Happy to discuss how GitHub actions work anytime you'd like 👍

**Comment by SeanKilleen** [comment]
@BrentOzar no actions needed now. I will see if merging this broke anything and will propose a fix if it did. I wanted you to know that my PR was designed to prevent breaking anything but by merging it without doing what I proposed, things ironically are more at risk of breaking. It's a lesson learned for next time on how GitHub actions work.

I know you work hard; in the future, don't merge anything from me you don't feel comfortable with. I'm always fine to talk things through and explain what I mean even if it means another round of waiting. I could have posted a screenshot with what to click.

**Comment by SeanKilleen** [comment]
✅🎉 builds all passed. You now have tests running across 2017, 2019, and 2022.

**Comment by BrentOzar** [comment]
Great, thanks man!

**Pull request merged**
