### PR TITLE
Extended/Added indexing to SqlServerVersion.sql.

### PR DESCRIPTION
**Pull request by idexxedi**
Fixes # .

Changes proposed in this pull request:
 Add Indexing (Cluster Index) to the table holding the SQL Server Version Data. Using a Unique integer and in sequential order, from oldest version starting with 1 to the newest version to keep the sort order unchanged. 

How to test this code:
 SqlServerVersion.sql against a database.

Has been tested on (remove any that don't apply):
 - SQL Server 2014

### CODE REVIEW

**Comment by BlitzErik** [comment]
Hi!

Thanks for taking the time to contribute some code. Can you make sure you've read the [contributing guide](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md) first? We really do encourage people to open issues for the changes they'd like to make first.

Thanks,
Erik

**Comment by idexxedi** [comment]
Hi Erik, I am deeply sorry not to fully followed the guide. I did read the whole doc and only using the guide I was able to upload the code but I just now realized that I simply missed the "opening issue" part. By the way, this was my first ever contribution on github repository and co. and I am very new to all of the process. I hope I will learn much more in the future

**Comment by BlitzErik** [comment]
No worries, just gotta make sure everyone follows the same process.

Thanks!

**Comment by BlitzErik** [comment]
Looking at your change -- Since this is a table that's going to get dropped/truncated and re-inserted to regularly, it's not really going to benefit from indexing. The number of rows is just too small.

Thanks, though.

**Pull request closed without merging**
