### PR TITLE
Restore from Multiple backup paths

### PR DESCRIPTION
**Pull request by CubsRep**
- #2180 
- Added `OFFILNE` option to `@ExistingDBAction` parameter. Flag Id = 4

### CODE REVIEW

**Comment by CubsRep** [comment]
@BrentOzar - PR opened for review

**Comment by BrentOzar** [comment]
OK, thanks! I don't use sp_DatabaseRestore personally, so can you maybe hop into the Slack room and get other folks to do testing on it as well? There are other folks who use it who may be able to help. Thanks!

**Comment by reharmsen** [comment]
> 
> 
> OK, thanks! I don't use sp_DatabaseRestore personally, so can you maybe hop into the Slack room and get other folks to do testing on it as well? There are other folks who use it who may be able to help. Thanks!

I like the idea of being able to restore striped backups.
Would love to try this in our environment to see whether I would be able to speedup backup and restore procedures.
Unfortunately I am not able to set this up, in the near future... might be February (or later) before I have the ability and time

**Comment by CubsRep** [comment]
I have had sync issues with the current PR.. so opened new #2241 for review and testing purposes

**Pull request closed without merging**
