### PR TITLE
Standardizing @Help behavior

### PR DESCRIPTION
**Pull request by ToddChitt**
Standard behavior for parameter @Help = 1 should be to run the PRINT statement(s) and nothing else.
Several blitz procedures were already coded this way. 
Added BEGIN / RETRUN / END lines to wrap the PRINT statements.

### CODE REVIEW

**Comment by BrentOzar** [comment]
There we go! Thanks. I'll review this this week.

**Comment by ToddChitt** [comment]
Like  said, not big on Git. 
Thanks for your patience!

**Comment by ToddChitt** [comment]
Crap, did I just do something bad? Going to re-open.
Then I'm going to shut up.

**Review by BrentOzar — APPROVED** [review]
That's the trick! Thanks for the pull request, and good idea. Merged into the dev branch, and will be in the January release with credit to you in the release notes.

**Pull request merged**
