### PR TITLE
Modified sp_BlitzIndex script

### PR DESCRIPTION
**Pull request by eliprairie**
Suggested modifications to sp_BlitzIndex script regarding removal of "sanity"-related language. See readme file for more details.

### CODE REVIEW

**Comment by eliprairie** [comment]
Hi @Adedba -- This is my first time merging to a repo via pull request, so apologies in advance if I'm missing something! I am not seeing any options here for me to merge this PR; it says next to a green icon, "This branch has no conflicts with the base branch. Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests." Does this mean I am unable to merge with my current permissions? Are there any changes needed to these files? Thanks!

**Comment by BrentOzar** [comment]
No no, you're totally okay, Wren. Ade is just assigning you credit for your work. No changes needed for now. Sorry about the delay on this!---Tiny glass keyboardTypos flowing like riversAs winter snow thawsOn Feb 3, 2023, at 3:46 PM, W. Eli Hayes ***@***.***> wrote:﻿
Hi @Adedba -- This is my first time merging to a repo via pull request, so apologies in advance if I'm missing something! I am not seeing any options here for me to merge this PR; it says next to a green icon, "This branch has no conflicts with the base branch. Only those with write access to this repository can merge pull requests." Does this mean I am unable to merge with my current permissions? Are there any changes needed to these files? Thanks!

**Comment by eliprairie** [comment]
No worries @BrentOzar , thank you for the clarification! :) Really happy to have been able to contribute!

**Comment by BrentOzar** [comment]
Closing this because I've replaced it with another pull request, and I'll work through that one. You'll be credited in the release notes though. Thanks!

**Pull request closed without merging**
