### PR TITLE
Added PlanGenerationNum to output for @expertmode=0

### PR DESCRIPTION
**Pull request by tlovie**
Added PlanGenerationNum to @expertmode=0 call for sp_BlitzCache

### CODE REVIEW

**Comment by tlovie** [comment]
wait on this - this isn't quite so simple.

**Comment by tlovie** [comment]
ok - so that last commit has it handled.

**Review by BrentOzar — APPROVED** [review]
Nice work! I always forget about the SortOrder = 'all' too.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merged into the dev branch, will be in the Feb release with credit to you in the release notes.

**Pull request merged**
