### PR TITLE
Blitzcache erik multiple

### PR DESCRIPTION
**Pull request by BlitzErik**
THIS RULES OK

### CODE REVIEW

**Comment by BlitzErik** [comment]
Pictures to prove it:

image

image

**Comment by BrentOzar** [comment]
DAAAAAAANG SON

Not gonna lie, the memory grant improvements get me more excited than two for one night at Cliff Lede. This is fantastic.

**Comment by BlitzErik** [comment]
Yeah! I need to add something to raise an error if the version is wrong. That's easy though. I'll add it tomorrow morning.

**Comment by BlitzErik** [comment]
How to repro and test this:

If you're using StackOverflow, you can run these queries:

```
SELECT [u].[DisplayName], SUM([u].[DownVotes]), SUM([u].[UpVotes])  
FROM [dbo].[Users] AS [u]  
WHERE [u].[UpVotes] > 1000  
AND [u].[DownVotes] > 1000  
AND [u].[Views] >= 100  
AND [u].[LastAccessDate] >= '2014-01-01'  
GROUP BY [u].[DisplayName]

SELECT [u].[DisplayName], SUM([u].[DownVotes]), SUM([u].[UpVotes])  
FROM [dbo].[Users] AS [u]  
WHERE [u].[Age] < 50  
AND [u].[DownVotes] > 1000  
AND [u].[Views] >= 100  
GROUP BY [u].[DisplayName]

SELECT [u].[DisplayName], SUM([u].[DownVotes]), SUM([u].[UpVotes])  
FROM [dbo].[Users] AS [u]  
WHERE [u].[UpVotes] > 1000  
AND [u].[DownVotes] > 1000  
AND [u].[Views] >= 100  
AND [u].[CreationDate] >= '2014-01-01'  
GROUP BY [u].[DisplayName]
```

They should all result in some large but unused memory grants, like these:
image

**Comment by BrentOzar** [comment]
Can you test this in all the machines in the lab? The 2016 one is showing the memory grant columns (the pictured above ones) as all nulls.

For example, ran this in ConsumeMassQuantities1:

CREATE TABLE dbo.Stuffing (ID INT IDENTITY(1,1) PRIMARY KEY CLUSTERED, Stuff CHAR(6000));
INSERT INTO dbo.Stuffing (Stuff) SELECT 'Stuff' FROM sys.all_columns;
GO
SELECT * FROM dbo.Stuffing ORDER BY Stuff DESC;
GO

While that SELECT was running, I checked this:

SELECT * FROM sys.dm_exec_query_memory_grants

And it showed grants. But when I run this:

sp_BlitzCache  @ExpertMode = 1, @SortOrder  = 'memory grant'

The Serial Desired and Serial Required columns are populated, but the rest aren't:

**Comment by BlitzErik** [comment]
This is fixed in the last commit! Working in AWS 2016 now. Will still fail on 2014 because versions.

**Pull request merged**
