### PR TITLE
Ola Hallengren scripts must be installed in the same database as Firs…

### PR DESCRIPTION
**Pull request by nick-fotopoulos**
…t Responder Kit.

Updated pull request. All unnecessary modifications have been removed, only functional changes remain. First Responder Kit will now look for Ola Hallengren scripts in the same database it's installed in.

### CODE REVIEW

**Comment by nick-fotopoulos** [comment]
Issue #3009

**Comment by wycislo** [comment]
I will work to verify this on RDS tomorrow.

**Comment by BrentOzar** [comment]
Looking good. Does it work on RDS?

**Comment by wycislo** [comment]
I made a copy of sp_allnightlog and compiled into RDS DBATools database. 

Commands completed successfully.

Completion time: 2021-11-22T13:25:45.0771998-06:00

-- I found references to xp_cmdshell in sp_allnightlog. Those will not run in RDS due to Amazon security 

xp_cmdshell is disabled on RDS and Amazon will not let you enable this procedure. 

configuration_id	name	value	minimum	maximum	value_in_use	description	is_dynamic	is_advanced
16390	xp_cmdshell	0	0	1	0	Enable or disable command shell	1	1

Msg 15247, Level 16, State 1, Procedure sp_configure, Line 105 [Batch Start Line 2]
User does not have permission to perform this action.
Msg 5812, Level 14, State 1, Line 5
You do not have permission to run the RECONFIGURE statement.
Msg 15247, Level 16, State 1, Procedure sp_configure, Line 105 [Batch Start Line 2]
User does not have permission to perform this action.
Msg 5812, Level 14, State 1, Line 8
You do not have permission to run the RECONFIGURE statement.

Completion time: 2021-11-22T13:38:58.0065416-06:00


exec DBATools.dbo.sp_AllNightLog_Setup @RunSetup =1;

/*------------------------

exec DBATools.dbo.sp_AllNightLog_Setup @RunSetup =1;
------------------------*/
xp_cmdshell must be enabled so we can get directory contents to check for new databases to restore.

Completion time: 2021-11-22T13:53:38.7464455-06:00

**Comment by wycislo** [comment]
1) I am able to compile the new fix on RDS to a dba created database. I call mine DBATools. I have compiled ola.hallengren's scripts into this database. 
2) The fix will compile but not run in RDS

**Comment by wycislo** [comment]
I am the DBA Admin on RDS

-- show current user
select current_user
----
(No column name)
admin
--
/*------------------------
-- show server permissions 
SELECT * FROM fn_my_permissions(NULL, 'SERVER'); 
-- show permissions for admin
------------------------*/

(16 rows affected)

Completion time: 2021-11-22T14:00:06.4498897-06:00


entity_name	subentity_name	permission_name
server		CONNECT SQL
server		CREATE ANY DATABASE
server		ALTER ANY LOGIN
server		ALTER ANY CREDENTIAL
server		ALTER ANY LINKED SERVER
server		ALTER ANY CONNECTION
server		ALTER TRACE
server		ADMINISTER BULK OPERATIONS
server		VIEW ANY DATABASE
server		VIEW ANY DEFINITION
server		VIEW SERVER STATE
server		ALTER SERVER STATE
server		ALTER ANY SERVER AUDIT
server		CREATE SERVER ROLE
server		ALTER ANY SERVER ROLE
server		ALTER ANY EVENT SESSION


---

/*------------------------
-- show permissions for admin
SELECT * FROM fn_my_permissions('admin', 'USER');  
------------------------*/

(4 rows affected)

Completion time: 2021-11-22T14:00:49.6891127-06:00

entity_name	subentity_name	permission_name
admin		IMPERSONATE
admin		VIEW DEFINITION
admin		ALTER
admin		CONTROL

**Comment by nick-fotopoulos** [comment]
@wycislo  xp_cmdshell is required for AllNightLog. No changes were made in this PL regarding xp_cmdshell.

**Review by BrentOzar — APPROVED** [review]
Thanks for the pull request. Looks good - I haven't tested it myself because I don't use sp_AllNightLog these days, but conceptually the changes make sense. Merging into the dev branch, will be in the next release with credit to you in the release notes.

**Pull request merged**
