### PR TITLE
Add SQL Server Version script

### LINKED ISSUE #1539: New script proposal: generate a table with SQL Server versions
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
We don't currently have a way to check to see if there are updates available for a SQL Server. We do have an "unsupported version" warning in sp_Blitz, but that only checks for truly unsupported - not whether there's an update available.

To build something really reusable, I'm proposing we create a script to build a table with columns for:

- Major version number
- Minor version number
- Branch (RTM, SP1, SP2, SP3)
- URL (for the KB article for this build number)
- ReleaseDate
- MainstreamSupportEndDate
- ExtendedSupportEndDate
- Major version name (SQL Server 2016)
- Minor version name (Service Pack 1 Cumulative Update 3)

The script would create the table if it doesn't already exist, and then add rows if they don't exist. Thoughts about the definition of the table?

**Sample deliverable, pseudocode:**

```
IF EXISTS dbo.SQLServerVersions THEN DROP TABLE dbo.SQLServerVersions;
CREATE TABLE dbo.SQLServerVersions (MajorVersionNumber, MinorVersionNumber, Branch, URL, ReleaseDate, MainstreamSupportEndDate, ExtendedSupportEndDate);
INSERT INTO dbo.SQLServerVersions VALUES (blah blah blah blah);
INSERT INTO dbo.SQLServerVersions VALUES (blah blah blah blah);
INSERT INTO dbo.SQLServerVersions VALUES (blah blah blah blah);
INSERT INTO dbo.SQLServerVersions VALUES (blah blah blah blah);
GO
```

### PR DESCRIPTION
**Pull request by jadarnel27**
Add a script to create and populate a table of SQL Server version information.

Fixes #1539.

Changes proposed in this pull request:
 - Add a script to the project that can be used to create and populate a reference table of SQL Server version and support information

How to test this code:
 - Run the script SqlServerVersions.sql (via SSMS, or your other favorite ways of executing T-SQL) against an existing database with an existing dbo schema

Has been tested on (remove any that don't apply):

 - SQL Server 2008 R2
 - SQL Server 2012
 - SQL Server 2014
 - SQL Server 2017
 - SQL Server 2016

Not yet tested on:

 - Case-sensitive SQL Server instance
 - SQL Server 2008
 - Amazon RDS
 - Azure SQL DB

### CODE REVIEW

**Comment by jadarnel27** [comment]
Just pushed:

 - the 2008 builds, 
 - the 2016 and 2017 RTM (which are missing from the MS support pages for some reason), and 

Also tested on all of the versions of SQL Server that I have readily available to me (and updated the original PR comment).  I'll see if I can get some help testing on the other ones.

**Comment by SQLJeet** [comment]
Tested this and merged into my instance populating script. It works on SQL 2008 and case-sensitive SQL server instances. I have had no issues running it and found one of my servers needed to be updated. Thank you for writing this.

**Comment by BlitzErik** [comment]
@jadarnel27 would you mind sharing the app you wrote to do the scraping? It doesn't even have to be in this repo, you can start your own GitHub repo for it. Just somewhere other folks can access it, avoiding the whole "one guy gets hit by a bus" thing.

I love having this, I just don't wanna have to bug you every time it needs updating

p.s. Watch out for that bus

**Comment by jadarnel27** [comment]
@SQLJeet glad it was helpful!

@BlitzErik Absolutely!  This slipped off my radar, I'll plan on pushing that code up to a new repo this weekend.  I'll ask Joe for tips on bus avoidance.  Heck, we'd be in bad shape if just my laptop were hit by a bus at this point.

**Comment by jadarnel27** [comment]
@BlitzErik I've pushed the code up here: https://github.com/jadarnel27/SqlServerVersionScript

Right now it just outputs the script to a console window as v1, but it's there 😃

**Comment by BlitzErik** [comment]
@jadarnel27  awesome! thanks!

**Pull request merged**
