### PR TITLE
#3377 Added a check for sp_MSgetalertinfo

### LINKED ISSUE #3377: [sp_Blitz] [Bug] Permissions checks are not working as intended
**Version of the script**
8.17
20231010

**What is the current behavior?**
Mea culpa, some of the fixes I made for the permission checks are not working.
😢 

* #3360 xp_regread doesn't play nice with a TRY CATCH block, so we just have to swallow those errors, they are not breaking the run, they just annoy me in the messages tab but, oh well, that's what we get for using an undocumented stored procedure.
* #3358 the permission check for the msdb database is to broad
* Forgot the add a check for [master].[dbo].[sp_MSgetalertinfo]

**What is the expected behavior?**
Fix the code to correct the issue I introduced.
* xp_regread, it gets the `@powerScheme` alright after the first error. The cpu speed not so well. Going to ISNULL the speed to UNKW
* add additional permission check for the msdb database
* add permission checkfor [master].[dbo].[sp_MSgetalertinfo]

Will be separate Pull requests per fix.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Same errors different day, thus more fixes.

### PR DESCRIPTION
**Pull request by Montro1981**
Fixes #3377
Added a permission check for sp_MSgetalertinfo.
The change is similar to PR #3359 for the Invalid Logins, did change the `@AlertInfo` table to a temp table `#AlertInfo` and added it to the clean up steps.

### CODE REVIEW

**Comment by BrentOzar** [comment]
@Montro1981 can you resolve the conflicts between this and your other changes first? Sorry about that.

**Comment by Montro1981** [comment]
@BrentOzar Will look at it tomorrow (European time)

**Comment by Montro1981** [comment]
@BrentOzar 
Conflict resolved, tested the deployment and `EXEC [dbo].[sp_Blitz] @CheckUserDatabaseObjects = 1` didn't throw any errors.

My name is Martin. You commented on it on Twitch last night I couldn't watch it live.

**Review by BrentOzar — APPROVED** [review]
Thanks for the modified pull request! Looks good, works on my machine, heh. Merging into dev, will be in the next release with credit to you in the release notes.

**Pull request merged**
