### PR TITLE
Chore: Add EditorConfig

### PR DESCRIPTION
**Pull request by nschonni**
Partial for #287
Autoconvert spaces to tabs, but no manual intervention for existing incorrect indenting levels

### CODE REVIEW

**Comment by nschonni** [comment]
If you look at the whitespace insensitive view https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/337/files?w=1 you'll see that the changes besides the config are indentation only. Might still want to spot check to see if there is trimmed significant whitespace.

**Comment by BrentOzar** [comment]
Can you do a pull request with only the EditorConfig? I totally appreciate that you did the first pass on spaces to tabs, but other folks have code changes going on in the other stored procs, so I'd rather be safe than sorry on the merge.

I'd take your EditorConfig and just check it in myself, but I wanna make sure you get credit on the leaderboard. :-D

**Comment by BrentOzar** [comment]
(And I'm excited on this one - setting up Visual Studio Code with the editorconfig plugin, and gonna start doing my T-SQL editing in there.)

**Comment by nschonni** [comment]
Ok, rebase and repushed

**Pull request merged**
