### PR TITLE
Uninstaller Script

### PR DESCRIPTION
**Pull request by EmanueleMeazzo**
Fulfills request #2080 

Deletes all the FirstResponderKit procedures from the current DB or all DBs via parameter

### CODE REVIEW

**Comment by BrentOzar** [comment]
Hmm, there are a couple of files in here - did you mean to submit something with sp_BlitzJobInfo?

**Comment by EmanueleMeazzo** [comment]
Nope, just submitting the unistaller script now
sp_BlitzJobInfo was a side project of mine originally for a PowerBI report, I'll add it to this repository eventually in the future; I hope that isn't an issue for this Pull, I wasn't able to tell github to ignore everything but the script

**Comment by BrentOzar** [comment]
Yeah, you may need to squash your commits or something - click on the top of this page on the "Files changed" and note that it shows 2. This might not be a problem, but I'm just hesitant to take the commit in this current state. (I just only have so many hours a day to troubleshoot if a pull request goes wrong, and I don't want to mess up the main repo.)

**Comment by EmanueleMeazzo** [comment]
Squashing commits still adds commits to the pull request, opening another clean one reabasing the branch

**Pull request closed without merging**
